INSERT INTO unidade (nome, data_cadastro, data_alteracao) VALUES
('Diretoria Administrativa', localtimestamp, localtimestamp),
('Diretoria de Recursos Humanos', localtimestamp, localtimestamp),
('Diretoria de Tecnologia da Informação e Comunicação', localtimestamp, localtimestamp),
('Diretoria de Gestão Estratégica e Orçamentária', localtimestamp, localtimestamp),
('Diretoria Financeira', localtimestamp, localtimestamp),
('Divisão de Auditoria Interna', localtimestamp, localtimestamp),
('Escola Superior do Ministério Público', localtimestamp, localtimestamp),
('Centro de Apoio Operacional Direitos Humanos', localtimestamp, localtimestamp),
('Centro de Apoio Operacional Educação', localtimestamp, localtimestamp),
('Centro de Apoio Operacional Infância e Adolescência', localtimestamp, localtimestamp),
('Centro de Apoio Operacional Meio Ambiente', localtimestamp, localtimestamp),
('Centro de Apoio Operacional Mulher', localtimestamp, localtimestamp),
('Centro de Apoio Operacional Patrimônio Público', localtimestamp, localtimestamp),
('Centro de Apoio Operacional Saúde', localtimestamp, localtimestamp),
('Centro de Apoio Operacional São Francisco', localtimestamp, localtimestamp),
('Centro de Apoio Operacional Segurança Pública', localtimestamp, localtimestamp),
('Centro de Apoio Operacional Atividade Criminal', localtimestamp, localtimestamp),
('Centro Médico', localtimestamp, localtimestamp),
('Coordenadoria Permanente de Autocomposição e Paz', localtimestamp, localtimestamp),
('Coordenadoria de Apoio aos Promotores Eleitorais', localtimestamp, localtimestamp),
('Coordenadoria de Documentação e Memória', localtimestamp, localtimestamp),
('Coordenadoria-Geral', localtimestamp, localtimestamp),
('Corregedoria-Geral', localtimestamp, localtimestamp),
('Divisão de Comunicação, Cerimonial e Eventos', localtimestamp, localtimestamp),
('Divisão de Perícia Contábil', localtimestamp, localtimestamp),
('Divisão de Perícia Técnica', localtimestamp, localtimestamp),
('Divisão de Equipe Interdisciplinar', localtimestamp, localtimestamp),
('Gabinete Procuradoria-Geral', localtimestamp, localtimestamp),
('Grupo de Atuação Especial de Combate ao Crime Organizado', localtimestamp, localtimestamp),
('Gabinete de Segurança Institucional', localtimestamp, localtimestamp),
('Ouvidoria', localtimestamp, localtimestamp),
('Promotoria de Controle Externo', localtimestamp, localtimestamp),
('Promotoria de Defesa da Saúde', localtimestamp, localtimestamp),
('Promotoria de Direitos do Cidadão', localtimestamp, localtimestamp),
('Secretaria-Geral', localtimestamp, localtimestamp),
('Subprocuradoria-Geral', localtimestamp, localtimestamp);

INSERT INTO tipo_lancamento (nome, data_cadastro, data_alteracao) VALUES
('Proposta Inicial da Unidade', localtimestamp, localtimestamp),
('Aprovação do Colégio de Procuradores de Justiça', localtimestamp, localtimestamp),
('Aprovação do Governo (Cota Orçamentária)', localtimestamp, localtimestamp),
('Revisão da Proposta Inicial da Unidade', localtimestamp, localtimestamp),
('Alteração da Revisão da Proposta Inicial da Unidade', localtimestamp, localtimestamp),
('Remanejamento', localtimestamp, localtimestamp),
('Crédito Suplementar Interno', localtimestamp, localtimestamp),
('Crédito Suplementar Entrada', localtimestamp, localtimestamp),
('Crédito Suplementar Saída', localtimestamp, localtimestamp),
('Crédito Extraordinário Interno', localtimestamp, localtimestamp),
('Crédito Extraordinário Entrada', localtimestamp, localtimestamp),
('Crédito Extraordinário Saída', localtimestamp, localtimestamp),
('Crédito Especial Interno', localtimestamp, localtimestamp),
('Crédito Especial Entrada', localtimestamp, localtimestamp),
('Crédito Especial Saída', localtimestamp, localtimestamp),
('Transferência', localtimestamp, localtimestamp),
('Reserva de Dotação', localtimestamp, localtimestamp),
('Alteração de Reserva de Dotação', localtimestamp, localtimestamp),
('Apostilamento', localtimestamp, localtimestamp),
('Alteração de Apostilamento', localtimestamp, localtimestamp),
('Empenho COM Reserva de Dotação', localtimestamp, localtimestamp),
('Empenho SEM Reserva de Dotação', localtimestamp, localtimestamp),
('Alteração de Empenho', localtimestamp, localtimestamp),
('Despesa Não Prevista', localtimestamp, localtimestamp);

INSERT INTO solicitante (nome, data_cadastro, data_alteracao) VALUES
('Diretoria Administrativa', localtimestamp, localtimestamp),
('Diretoria de Recursos Humanos', localtimestamp, localtimestamp),
('Diretoria de Tecnologia da Informação e Comunicação)', localtimestamp, localtimestamp),
('Diretoria de Gestão Estratégica e Orçamentária', localtimestamp, localtimestamp),
('Divisão de Auditoria Interna', localtimestamp, localtimestamp),
('Escola Superior do Ministério Público', localtimestamp, localtimestamp),
('Procuradoria-Geral de Justiça', localtimestamp, localtimestamp),
('Subprocuradoria-Geral de Justiça', localtimestamp, localtimestamp),
('Coordenadoria Recursal', localtimestamp, localtimestamp),
('Gabinete de Segurança Institucional', localtimestamp, localtimestamp),
('Comissão de Concurso', localtimestamp, localtimestamp),
('Gabinete do Grupo de Atuação Especial de Combate ao Crime Organizado', localtimestamp, localtimestamp),
('Coordenadoria Permanente de Autocomposição e Paz', localtimestamp, localtimestamp),
('Coordenadoria de Promoção de Igualdade Étnico-Racial', localtimestamp, localtimestamp),
('Cartório 2º Grau', localtimestamp, localtimestamp),
('Divisão de Comunicação, Cerimonial e Eventos', localtimestamp, localtimestamp),
('Secretaria-Geral', localtimestamp, localtimestamp),
('Grupo de Apoio Operacional da Secretaria Geral', localtimestamp, localtimestamp),
('Assessoria Jurídica', localtimestamp, localtimestamp),
('Centro Médico', localtimestamp, localtimestamp),
('Central de Expedições de Diligências', localtimestamp, localtimestamp),
('Divisão de Material', localtimestamp, localtimestamp),
('Divisão de Apoio Administrativo', localtimestamp, localtimestamp),
('Divisão de Engenharia e Manutenção', localtimestamp, localtimestamp),
('Divisão de Patrimônio', localtimestamp, localtimestamp),
('Diretoria Financeira', localtimestamp, localtimestamp),
('Corregedoria-Geral', localtimestamp, localtimestamp),
('Coordenadoria-Geral', localtimestamp, localtimestamp),
('Ouvidoria', localtimestamp, localtimestamp),
('Grupo de Combate a Improbidade Administrativa', localtimestamp, localtimestamp),
('Colégio de Procuradores de Justiça', localtimestamp, localtimestamp),
('Conselho Superior do Ministério Público', localtimestamp, localtimestamp),
('Centro de Apoio Operacional de Segurança Pública', localtimestamp, localtimestamp),
('Centro de Apoio Operacional da Infância e da Adolescência', localtimestamp, localtimestamp),
('Centro de Apoio Operacional de Defesa do Patrimônio Público, da Ordem Tributária e do Terceiro Setor', localtimestamp, localtimestamp),
('Centro de Apoio Operacional Atividades Cíveis e Criminais', localtimestamp, localtimestamp),
('Divisão de Perícia Técnica', localtimestamp, localtimestamp),
('Divisão de Perícia Contábil', localtimestamp, localtimestamp),
('Divisão de Equipe Interdisciplinar', localtimestamp, localtimestamp),
('Centro de Apoio Operacional de Defesa dos Direitos Humanos', localtimestamp, localtimestamp),
('Centro de Apoio Operacional de Proteção ao Rio São Francisco e às Nascentes', localtimestamp, localtimestamp),
('Centro de Apoio Operacional dos Direitos à Educação', localtimestamp, localtimestamp),
('Centro de Apoio Operacional dos Direitos à Saúde', localtimestamp, localtimestamp),
('Centro de Apoio Operacional do Meio Ambiente, Urbanismo, Patrimônio Social e Cultural', localtimestamp, localtimestamp),
('Centro de Apoio Operacional dos Direitos da Mulher', localtimestamp, localtimestamp),
('Coordenadoria de Apoio aos Promotores Eleitorais', localtimestamp, localtimestamp),
('1ª Procuradoria de Justiça', localtimestamp, localtimestamp),
('2ª Procuradoria de Justiça', localtimestamp, localtimestamp),
('3ª Procuradoria de Justiça', localtimestamp, localtimestamp),
('4ª Procuradoria de Justiça', localtimestamp, localtimestamp),
('5ª Procuradoria de Justiça', localtimestamp, localtimestamp),
('6ª Procuradoria de Justiça', localtimestamp, localtimestamp),
('7ª Procuradoria de Justiça', localtimestamp, localtimestamp),
('8ª Procuradoria de Justiça', localtimestamp, localtimestamp),
('9ª Procuradoria de Justiça', localtimestamp, localtimestamp),
('10ª Procuradoria de Justiça', localtimestamp, localtimestamp),
('11ª Procuradoria de Justiça', localtimestamp, localtimestamp),
('12ª Procuradoria de Justiça', localtimestamp, localtimestamp),
('13ª Procuradoria de Justiça', localtimestamp, localtimestamp),
('14ª Procuradoria de Justiça', localtimestamp, localtimestamp),
('1ª Promotoria Direitos do Cidadão - Defesa do Patrimônio Público e na área de Previdência Pública', localtimestamp, localtimestamp),
('2ª Promotoria Direitos do Cidadão - Defesa dos Direitos à Saúde', localtimestamp, localtimestamp),
('3ª Promotoria Direitos do Cidadão - Controle Externo da Atividade policial e em Questões Agrárias', localtimestamp, localtimestamp),
('4ª Promotoria Direitos do Cidadão - Defesa do Acidentado do Trabalho, do Idoso, do Deficiente, dos Direitos Humanos em Geral e dos Direitos à Assistência Social', localtimestamp, localtimestamp),
('5ª Promotoria Direitos do Cidadão - Controle e Fiscalização do Terceiro Setor ', localtimestamp, localtimestamp),
('6º Promotoria Direitos do Cidadão - Defesa do Direito à Educação', localtimestamp, localtimestamp),
('7ª Promotoria Direitos do Cidadão - Defesa da Ordem Tributária', localtimestamp, localtimestamp),
('8ª Promotoria Direitos do Cidadão - Defesa dos Direitos da Criança e do Adolescente', localtimestamp, localtimestamp),
('9ª Promotoria Direitos do Cidadão - Defesa dos Direitos à Saúde', localtimestamp, localtimestamp),
('10ª Promotoria Direitos do Cidadão - Defesa do Meio Ambiente, Urbanismo, Patrimônio Social e Cultural e dos Serviços de Relevância Pública', localtimestamp, localtimestamp),
('1ª Promotoria (1ª, 2º, 4º, 6º, 7º, 8º, 9º Varas Cíveis) de Aracaju', localtimestamp, localtimestamp),
('2ª Promotoria (14ª Vara Cível) de Aracaju', localtimestamp, localtimestamp),
('3ª Promotoria Cível de Aracaju (5ª, 10ª, 11ª, 13ª, 15ª e 21ª Varas Cíveis) de Aracaju', localtimestamp, localtimestamp),
('1ª Promotoria da Curadoria da Fazenda Pública (3ª Vara Cível) de Aracaju', localtimestamp, localtimestamp),
('2ª Promotoria da Curadoria da Fazenda Pública (12ª Vara Cível) de Aracaju', localtimestamp, localtimestamp),
('3ª Promotoria da Curadoria da Fazenda Pública (18ª Vara Cível) de Aracaju', localtimestamp, localtimestamp),
('4ª Promotoria da Curadoria da Fazenda Pública (Juizado Especial da Fazenda Pública) de Aracaju', localtimestamp, localtimestamp),
('1ª Promotoria Criminal (1ª Vara Criminal) de Aracaju', localtimestamp, localtimestamp),
('2ª Promotoria Criminal (2º Vara Criminal) de Aracaju', localtimestamp, localtimestamp),
('3ª Promotoria Criminal (3ª Vara Criminal) de Aracaju', localtimestamp, localtimestamp),
('4ª Promotoria Criminal (4ª Vara Criminal) de Aracaju', localtimestamp, localtimestamp),
('Promotoria de Defesa do Consumidor de Aracaju', localtimestamp, localtimestamp),
('5ª Promotoria Criminal (9ª Vara Criminal) de Aracaju', localtimestamp, localtimestamp),
('6ª Promotoria Criminal (11ª Vara Criminal - Juizado de Violência Doméstica contra a Mulher) de Aracaju', localtimestamp, localtimestamp),
('1ª Promotoria Do Tribunal do Júri (5ª Vara Criminal) de Aracaju', localtimestamp, localtimestamp),
('2ª Promotoria Do Tribunal do Júri  (8ª Vara Criminal) de Aracaju', localtimestamp, localtimestamp),
('3ª  Promotoria Do Tribunal do Júri (5ª Vara Criminal) de Aracaju', localtimestamp, localtimestamp),
('4ª  Promotoria Do Tribunal do Júri (8ª Vara Criminal) de Aracaju', localtimestamp, localtimestamp),
('Promotoria Militar (Auditoria Militar - 6º Vara Criminal) de Aracaju', localtimestamp, localtimestamp),
('1ª Promotoria das Execuções Criminais (7ª Vara Criminal) de Aracaju', localtimestamp, localtimestamp),
('3ª Promotoria das Execuções Criminais (7ª Vara Criminal) de Aracaju', localtimestamp, localtimestamp),
('Promotoria de Acidentes e de Delitos de Trânsito de Aracaju', localtimestamp, localtimestamp),
('1ª Promotoria da Curadoria da Infância e da Adolescência (Juizado da Infância e Juventude - 16ª Vara Cível) de Aracaju', localtimestamp, localtimestamp),
('2ª Promotoria da Curadoria da Infância e da Adolescência (Juizado da Infância e Juventude - 17ª Vara Cível) de Aracaju', localtimestamp, localtimestamp),
('5ª Promotoria Distrital - (5ª Vara de Assistência Judiciária - 26ª Vara Cível)', localtimestamp, localtimestamp),
('6ª Promotoria Distrital (6ª Vara de Assistência Judiciária - 27ª Vara Cível)', localtimestamp, localtimestamp),
('1ª Promotoria Distrital (1ª Vara de Assistência Judiciária - 19ª Vara Cível)', localtimestamp, localtimestamp),
('3ª Promotoria Distrital (3ª Vara de Assistência Judiciária - 24ª Vara Cível)', localtimestamp, localtimestamp),
('2ª Promotoria Distrital (2ª Vara de Assistência Judiciária - 23ª Vara Cível)', localtimestamp, localtimestamp);

INSERT INTO objetivo_estrategico (nome, data_cadastro, data_alteracao) VALUES
('Incrementar o diálogo e a atuação conjunta do MP com os órgãos públicos e instituições não governamentais de defesa do consumidor', localtimestamp, localtimestamp),
('Fortalecer as redes de atendimento a grupos vulneráveis junto aos Órgãos Públicos', localtimestamp, localtimestamp),
('Atuar na universalização do acesso à educação e à saúde com a prestação de serviços de qualidade', localtimestamp, localtimestamp),
('Aprimorar as atividades de combate à corrupção, defesa do patrimônio público e fiscalização do terceiro setor', localtimestamp, localtimestamp),
('Contribuir para a preservação do meio ambiente e patrimônio histórico e cultural e para o desenvolvimento urbano de forma sustentável, em sintonia com as demais instituições e com a sociedade em geral', localtimestamp, localtimestamp),
('Intensificar o combate à criminalidade e o efetivo controle externo da atividade policial', localtimestamp, localtimestamp),
('Aprimorar, informatizar e desburocratizar as rotinas administrativas', localtimestamp, localtimestamp),
('Potencializar práticas resolutivas da atuação ministerial', localtimestamp, localtimestamp),
('Aprimorar o processo de gestão e governança', localtimestamp, localtimestamp),
('Capacitar, valorizar e motivar todos que atuam na instituição', localtimestamp, localtimestamp),
('Promover a qualidade de vida no trabalho e a valorização dos Membros e Servidores', localtimestamp, localtimestamp),
('Aperfeiçoar a comunicação efetiva com a sociedade e o relacionamento institucional', localtimestamp, localtimestamp),
('Modernizar e adequar a infraestrutura física', localtimestamp, localtimestamp),
('Prover soluções de TI, entregando benefícios, mitigando riscos e otimizando recursos', localtimestamp, localtimestamp),
('Assegurar recursos orçamentários, otimizar sua alocação e aperfeiçoar o gerenciamento', localtimestamp, localtimestamp);

INSERT INTO tipo_transacao (nome, data_cadastro, data_alteracao) VALUES
('Débito', localtimestamp, localtimestamp),
('Crédito', localtimestamp, localtimestamp);

INSERT INTO grupo_despesa (nome, data_cadastro, data_alteracao) VALUES
('Pessoal', localtimestamp, localtimestamp),
('Outras Despesas Correntes', localtimestamp, localtimestamp);
('Investimentos', localtimestamp, localtimestamp);