INSERT INTO unidade (nome, data_cadastro, data_alteracao) VALUES
('Diretoria Administrativa', localtimestamp, localtimestamp),
('Diretoria de Recursos Humanos', localtimestamp, localtimestamp),
('Diretoria de Tecnologia da Informação e Comunicação', localtimestamp, localtimestamp),
('Diretoria de Gestão Estratégica e Orçamentária', localtimestamp, localtimestamp),
('Diretoria Financeira', localtimestamp, localtimestamp),
('Divisão de Auditoria Interna', localtimestamp, localtimestamp),
('Escola Superior do Ministério Público', localtimestamp, localtimestamp),
('Centro de Apoio Operacional Direitos Humanos', localtimestamp, localtimestamp),
('Centro de Apoio Operacional Educação', localtimestamp, localtimestamp),
('Centro de Apoio Operacional Infância e Adolescência', localtimestamp, localtimestamp),
('Centro de Apoio Operacional Meio Ambiente', localtimestamp, localtimestamp),
('Centro de Apoio Operacional Mulher', localtimestamp, localtimestamp),
('Centro de Apoio Operacional Patrimônio Público', localtimestamp, localtimestamp),
('Centro de Apoio Operacional Saúde', localtimestamp, localtimestamp),
('Centro de Apoio Operacional São Francisco', localtimestamp, localtimestamp),
('Centro de Apoio Operacional Segurança Pública', localtimestamp, localtimestamp),
('Centro de Apoio Operacional Atividade Criminal', localtimestamp, localtimestamp),
('Centro Médico', localtimestamp, localtimestamp),
('Coordenadoria Permanente de Autocomposição e Paz', localtimestamp, localtimestamp),
('Coordenadoria de Apoio aos Promotores Eleitorais', localtimestamp, localtimestamp),
('Coordenadoria de Documentação e Memória', localtimestamp, localtimestamp),
('Coordenadoria-Geral', localtimestamp, localtimestamp),
('Corregedoria-Geral', localtimestamp, localtimestamp),
('Divisão de Comunicação, Cerimonial e Eventos', localtimestamp, localtimestamp),
('Divisão de Perícia Contábil', localtimestamp, localtimestamp),
('Divisão de Perícia Técnica', localtimestamp, localtimestamp),
('Divisão de Equipe Interdisciplinar', localtimestamp, localtimestamp),
('Gabinete Procuradoria-Geral', localtimestamp, localtimestamp),
('Grupo de Atuação Especial de Combate ao Crime Organizado', localtimestamp, localtimestamp),
('Gabinete de Segurança Institucional', localtimestamp, localtimestamp),
('Ouvidoria', localtimestamp, localtimestamp),
('Promotoria de Controle Externo', localtimestamp, localtimestamp),
('Promotoria de Defesa da Saúde', localtimestamp, localtimestamp),
('Promotoria de Direitos do Cidadão', localtimestamp, localtimestamp),
('Secretaria-Geral', localtimestamp, localtimestamp),
('Subprocuradoria-Geral', localtimestamp, localtimestamp);

INSERT INTO tipo_lancamento (nome, data_cadastro, data_alteracao) VALUES
('Proposta Inicial da Unidade', localtimestamp, localtimestamp),
('Aprovação do Colégio de Procuradores de Justiça', localtimestamp, localtimestamp),
('Aprovação do Governo (Cota Orçamentária)', localtimestamp, localtimestamp),
('Revisão da Proposta Inicial da Unidade', localtimestamp, localtimestamp),
('Alteração da Revisão da Proposta Inicial da Unidade', localtimestamp, localtimestamp),
('Remanejamento', localtimestamp, localtimestamp),
('Crédito Suplementar Interno', localtimestamp, localtimestamp),
('Crédito Suplementar Entrada', localtimestamp, localtimestamp),
('Crédito Suplementar Saída', localtimestamp, localtimestamp),
('Crédito Extraordinário Interno', localtimestamp, localtimestamp),
('Crédito Extraordinário Entrada', localtimestamp, localtimestamp),
('Crédito Extraordinário Saída', localtimestamp, localtimestamp),
('Crédito Especial Interno', localtimestamp, localtimestamp),
('Crédito Especial Entrada', localtimestamp, localtimestamp),
('Crédito Especial Saída', localtimestamp, localtimestamp),
('Transferência', localtimestamp, localtimestamp),
('Reserva de Dotação', localtimestamp, localtimestamp),
('Alteração de Reserva de Dotação', localtimestamp, localtimestamp),
('Apostilamento', localtimestamp, localtimestamp),
('Alteração de Apostilamento', localtimestamp, localtimestamp),
('Empenho COM Reserva de Dotação', localtimestamp, localtimestamp),
('Empenho SEM Reserva de Dotação', localtimestamp, localtimestamp),
('Alteração de Empenho', localtimestamp, localtimestamp),
('Despesa Não Prevista', localtimestamp, localtimestamp);


